export const MICRO_SERVICES = {
  AUTH_SERVICE: {
    NAME: "AUTH_SERVICE",
    MESSAGE_EVENT: {
      VERIFY_KYC_CALLBACK: "VERIFY_KYC_CALLBACK",
      AADHAAR_GENERATE_OTP: "AADHAAR_GENERATE_OTP",
      AADHAAR_VERIFY_OTP: "AADHAAR_VERIFY_OTP",
    },
  },
  ASSET_SERVICE: {
    NAME: "ASSET_SERVICE",
    MESSAGE_EVENT: {
      CREATE_ASSET: "create_asset",
      UPDATE_ASSET: "update_asset",
      CREATE_DOCUMENT: "create_document",
      LIST_ASSETS: "find_all_assets",
      LIVE_ASSETS: "live_assets",
      BUY_ASSET: "buy_asset",
      FIND_ASSET: "find_one_asset",
      WISHLIST_ASSET: "wishlist_asset",
      FETCH_WISHLIST_ASSET: "fetch_wishlist_asset",
      FETCH_WISHLIST_ASSET_COUNT: "fetch_wishlist_asset_count",
      ASSET_VIEWS: "asset_views",
      FETCH_ASSET_VIEWS_COUNT: "fetch_asset_views_count",
      FETCH_ASSET_BY_STATUS: "fetch_status_by_status",
      REMOVE_ASSET: "remove_asset",
      FIND_ASSET_TAG: "find_asset_tag",
      QR_CODE_SCAN: "qr_code_scan",
      GET_USER_ASSET: "find_user_asset",
      CATEGORY_LIST: "category_list",
      DELETE_LISTINGS: "delete_listings",
      IMAGES_BY_CATEGORY: "find_image_asset",
      PRICE_HISTORY: "price_history",
      SOLD_ASSET: "sold_assets",
      SUBMISSION_COUNT: "submission_count",
      SUBMIT_EXCLUSIVE_ACCESS: "submit_exclusive_access",
      GET_FEATURE_ASSET: "feature_asset",
      GET_EXCLUSIVE_ACCESS: "get_exclusive_access",
      ASSET_PARTIAL_SEARCH: "asset_partial_search",
      ASSETS_DRAFT: "assets_draft",
      GET_ASSET_DRAFT: "get_asset_draft",
      DELETE_ASSET_DRAFT: "delete_asset_draft",
      FETCH_USER_COLLECTIONS: "fetch_user_collections",
      FETCH_USER_COLLECTIONS_COUNT: "fetch_user_collections_count",
      FETCH_ASSETS_SOLD_BY_USER: "fetch_assets_sold_by_user",
      FETCH_USER_ASSETS_FOR_SALE: "fetch_user_assets_for_sale",
      FETCH_ALL_NOTIFICATIONS: "fetch_all_notifications",
      READ_NOTIFICATION: "read_notification",
      READ_ALL_NOTIFICATIONS: "read_all_notifications",
      ASSET_LISTING: "asset_listing",
    },
  },
  PAYMENT_SERVICE: {
    NAME: "PAYMENT_SERVICE",
    MESSAGES_EVENTS: {
      BUY: "payments.buy",
      UPDATE_PAYMENT: "payments.update-payment",
      CREATE_STRIPE_ACCOUNT: "payments.create-stripe-account",
      WEBHOOK_EVENTS: "payments.events",
      STRIPE_ACCOUNT_STATUS: "payments.account-status",
      UPDATE_STRIPE_ACCOUNT: "payments.update-account",
      ORDERS: "payments.orders",
      CANCELLED_ORDER: "payments.cancelled_order",
      REWARDS_LIST: "rewards_list",
      CREATE_STRIPE_LOGIN_LINK: "payments.create_stripe_login_link",
    },
  },
};
