// TODO: Need to add message events name in future
export const MESSAGES_EVENTS = {
  GET_USER_DETAIL: "GET_USER_DETAIL",
  UPDATE_USER_DETAIL: "UPDATE_USER_DETAIL",
  INITIATE_KYC: "INITIATE_KYC",
  KYCAID_VERIFICATION_URL: "KYCAID_VERIFICATION_URL",
  KYC_DOCUMENTS: "KYC_DOCUMENTS",
  UPDATE_WALLET_ADDRESS: "UPDATE_WALLET_ADDRESS",
  SEND_CONTACT_EMAIL: "SEND_CONTACT_EMAIL",
  VERIFY_KYC_CALLBACK: "VERIFY_KYC_CALLBACK",
  AADHAAR_GENERATE_OTP: "AADHAAR_GENERATE_OTP",
  AADHAAR_VERIFY_OTP: "AADHAAR_VERIFY_OTP",
};
